version: '2.1'
services:

    mender-client:
        # Needs to be built in extra/mender-client-docker-addons
        image: mendersoftware/mender-client-docker-addons:master
        networks:
            - mender

networks:
    mender:
