version: '2.3'
services:

    mender-client:
        # Needs to be built in extra/mender-client-docker-addons
        image: mendersoftware/mender-client-docker-addons:mender-3.5.1
        networks:
            - mender

networks:
    mender:
