version: '2.1'
services:

    #
    # mender-devicemonitor
    #
    mender-devicemonitor:
        image: registry.mender.io/mendersoftware/devicemonitor:mender-3.1.0
        command: server --automigrate
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    mender-api-gateway:
      volumes:
        - ./config/traefik/traefik.monitor.yaml:/etc/traefik/config/traefik.monitor.yaml:ro

    mender-gui:
        environment:
            HAVE_MONITOR: 1
