version: '3.8'

services:
  azblob-container-setup:
    image: mcr.microsoft.com/azure-cli:2.40.0
    deploy:
      replicas: 0
    environment:
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
    entrypoint: [az, storage, container, create, -o, none, --fail-on-exist, -n]

  azblob-container-teardown:
    image: mcr.microsoft.com/azure-cli:2.40.0
    deploy:
      replicas: 0
    environment:
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
    entrypoint: [az, storage, container, delete, -o, none, --fail-not-exist, -n]
