services:
  mender-gateway:
    networks:
      - mender
      - mender_local
    volumes:
      - "./extra/mender-gateway/mender-gateway.conf:/mender-gateway.conf:ro"
    environment:
      - MENDER_GATEWAY_CONFFILE="/mender-gateway.conf"

networks:
    mender:
    mender_local:
